openapi: 3.1.1
info:
  title: ProyectoM2_MartinVelez API
  version: 1.0.0
  description: API para gestionar usuarios y publicaciones
  contact:
    name: Tu Nombre
    email: tu@email.com

servers:
  - url: http://localhost:3000
    description: Servidor de desarrollo
  - url: https:// ProyectoM2_MartinVelez.railway.app
    description: Servidor de producción
paths:
  /api/usuarios:
    get:
      summary: Obtener todos los usuarios
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usuario'

    post:
      summary: Crear usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Usuario creado

  /api/usuarios/{id}:
    get:
      summary: Obtener usuario por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '404':
          description: No encontrado

  /api/publicaciones:
    get:
      summary: Obtener publicaciones
      responses:
        '200':
          description: Lista de publicaciones

components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        bio:
          type: string

    Error:
      type: object
      properties:
        error:
          type: string