info:
  title: ProyectoM2_MartinVelez API
  version: 1.0.0
  description: API para gestionar autores y posts
  contact:
    name: Tu Nombre
    email: tu@email.com

    servers:
  - url: http://localhost:3000
    description: Servidor de desarrollo
  - url: https://api.ejemplo.com
    description: Servidor de producción

    paths:
  /usuarios:
    get:
      summary: Obtener todos los usuarios
      description: Devuelve una lista de todos los usuarios registrados.
      tags:
        - Usuarios  
      responses:
        '200':
          description: Lista de usuarios obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usuario'
        '500':
          description: Error al obtener usuarios

components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Juan Pérez
        email:
          type: string
          example: